function interfata(A,R,L,f,lista,N)


%Ecuatii

T=1./f; %perioada
t=0:T/1000:T*N; %vector pentru tmp
xl=2.*pi.*f.*L; %Reactanta L
z=sqrt(R^2+(xl.^2)); %impedanta totala
i=A./z; %curentul max din circuit
tau = L./R; %[tau]
ph=acosd(R/z); %arcsin pentru aflarea fazei
faza=(ph*pi)/180;

ir=(A/z)*sin(2*pi*f*t); %curent pe R
vr=i*R*sin(2*pi*f*t); %tensine pe R

vl=i*xl*sin(2*pi*f*t); %tensiune pe L
il=(A/z)*sin(2*pi*f*t+faza); %curent pe L

p=vl.*ir.^2;% puterea disipata de R [W]
WmL=(L.*il.^2)./2; % Energia magnetica stocata de L

figure('Name','Circuitul RL integrator',...
'Units','normalized',...
'Position',[0 0 1 1],...
'NumberTitle','off',...
'color', 'w');

gi=uimenu('Label','Documentatie');
uimenu(gi,'Label','Prezentare ppt','Callback','open prezentare_gac.pptx');
uimenu(gi,'Label','Autor','Callback','open autor.pdf');

%grup butoane modificare valori
param=uibuttongroup('Visible','on',...
              'BackgroundColor','w',...
              'ForegroundColor','black',...
              'FontSize',15,...
              'FontWeight','b',...
              'TitlePosition','centertop',...
              'Title','Valori ale circuitului',...
              'Position',[0.065 0.62 0.20 0.35]);
%Text si Edit R
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.1 0.65 0.10 0.3],...
          'BackgroundColor','w',...
          'FontSize',12,...
          'FontWeight','b',...
          'String','R',...
          'Parent',param); 

uicontrol('Style','Edit',...
          'Units','Normalized',...
          'Position',[0.4 0.850 0.4 0.1],...
           'BackgroundColor','w',...
          'FontSize',12,...
          'String',R,...
          'Parent',param,...
           'Callback','R=str2num(get(gco,''String'')),close;interfata(A,R,L,f,lista,N)');

       
 %conditie R
 if((R<=0))
    R=12;
    close();
    interfata(A,R,L,f,lista,N);
    disp('Valoare invalida (<=0)');

 end

%Text si Edit N
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.1 0.5 0.10 0.3],...
          'BackgroundColor','w',...
          'FontSize',12,...
          'FontWeight','b',...
          'Parent',param,...
          'String','N'); 

uicontrol('Style','Edit',...
          'Units','Normalized',...
          'Position',[0.4 0.7 0.4 0.1],...
           'BackgroundColor','w',...
          'FontSize',12,...
          'String',N,...
          'Parent',param,...
          'Callback','N=str2num(get(gco,''String'')),close;interfata(A,R,L,f,lista,N)');
       
      
        
 %conditie N
 if((N<=0))
    N=6;
    close();
    interfata(A,R,L,f,lista,N);
    disp('Valoare invalida (<=0)');

 end

 
%Text si Edit L
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.1 0.33 0.10 0.3],...
          'FontSize',12,...
          'BackgroundColor','w',...
          'FontWeight','b',...
          'Parent',param,... 
          'String','L');
      uicontrol('Style','Edit',...
          'Units','Normalized',...
          'Position',[0.4 0.52 0.4 0.1],...
          'BackgroundColor','w',...
          'FontSize',12,...
          'String',L,...
          'Parent',param,... 
           'Callback','L=str2num(get(gco,''String'')),close;interfata(A,R,L,f,lista,N)');
       
 %conditie L      
 if((L<=0))
    L=0.15;
    close();
    interfata(A,R,L,f,lista,N);
    disp('Valoare invalida (<=0)');
    
end      
%Text si Edit A
 uicontrol('Style','Text',...
           'Units','Normalized',...
           'Position',[0.1 0.13 0.10 0.3],...
           'BackgroundColor','w',...
           'FontSize',12,...
           'FontWeight','b',...
           'Parent',param,... 
           'String','A');
       
 uicontrol('Style','Edit',...
           'Units','Normalized',...
           'Position',[0.4 0.33 0.4 0.1],...
           'BackgroundColor','w',...
           'FontSize',12,...
           'String',A,...
           'Parent',param,... 
           'Callback','A=str2num(get(gco,''String'')),close;interfata(A,R,L,f,lista,N)');
       
%conditie A      
if((A<=0))
   	A=10;
    close();
    interfata(A,R,L,f,lista,N);
    disp('Valoare invalida (<=0)');
end
             
%Text si Edit f       
       uicontrol('Style','Text',...
           'Units','Normalized',...
           'Position',[0.1 0 0.10 0.2],...
           'BackgroundColor','w',...
           'FontSize',12,...
           'FontWeight','b',...
           'Parent',param,... 
           'String','f');
       
 uicontrol('Style','Edit',...
           'Units','Normalized',...
           'Position',[0.4 0.1 0.4 0.1],...
           'BackgroundColor','w',...
           'FontSize',12,...
           'String',f,...
           'Parent',param,... 
           'Callback','f=str2num(get(gco,''String'')),close;interfata(A,R,L,f,lista,N)');
%conditie f       
if((f<=0))
   	f=40;
    close();
    interfata(A,R,L,f,lista,N);
    disp('Valoare invalida (<=0)');
end
           

uicontrol('Style', 'pushbutton', 'String', 'Formule utilizate',...
        'Units', 'normalized',...
        'Position', [0.28 0.6 0.08 0.07],...
        'Callback', 'open formuleutilizate.pdf'); 

uicontrol('Style', 'pushbutton', 'String', 'Close (X)',...
        'Units', 'normalized',...
        'Position', [0.93 0.93 0.05 0.05],...
        'Callback', 'close');       
    
    
%grup butoane afisare date circuit
ecuatii=uibuttongroup('Visible','on',...
              'BackgroundColor','w',...
              'ForegroundColor','black',...
              'FontSize',15,...
              'FontWeight','b',...
              'TitlePosition','centertop',...
              'Title','Date despre circuit',...
              'Position',[0.065 0.25 0.20 0.35]);

uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.2,0.5,0.6,0.4],...
          'BackgroundColor','w',...
          'FontSize',12,...
          'FontWeight','b',...
          'Parent',ecuatii,...
          'String',['Xl = ',num2str(xl)]); 
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.2,0.35,0.55,0.4],...
          'BackgroundColor','w',...
          'FontSize',12,...
          'FontWeight','b',...
          'Parent',ecuatii,...
          'String',['Z total = ',num2str(z)]); 

      uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.2,0.20,0.55,0.4],...
          'BackgroundColor','w',...
          'FontSize',12,...
          'FontWeight','b',...
          'Parent',ecuatii,...
          'String',['tau = ',num2str(tau),'ns']);  
      
      uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.2,0.05,0.6, 0.4],...
          'BackgroundColor','w',...
          'FontSize',12,...
          'FontWeight','b',...
          'Parent',ecuatii,...
          'String',['Faza = ',num2str(fix(ph)),' grade ']); 
       
        
popup=uicontrol('Style','PopupMenu',...
'Units','normalized',...
'Position',[0.05 0.08 0.26 0.1],...
'String','Afisare circuit|Afisare tensiune si curent pe rezistenta|Afisare tensiune si curent pe bobina|Diagrama Putere',...
'FontSize',15,...
'ForegroundColor','red',...
'Callback','lista=get(gco,''value''),close;interfata(A,R,L,f,lista,N)');




switch(lista)
    case 1 %imagine
        g=imread('circuit_RL_lucan.jpg');
image(g);
set(gca,'Position',[0.35 0.25 0.6 0.55]);
axis off;

rfigura=uicontrol('Style','Edit',...
          'Units','Normalized',...
          'Position',[0.55 0.642 0.05 0.04],...
           'BackgroundColor','w',...
          'FontSize',12,...
          'String',R,...
          'Callback','R=str2num(get(gco,''String'')),close;interfata(A,R,L,f,lista,N)');
      
      lfigura=uicontrol('Style','Edit',...
          'Units','Normalized',...
          'Position',[0.865 0.54 0.04 0.04],...
           'BackgroundColor','w',...
          'FontSize',12,...
          'String',L,...
          'Callback','L=str2num(get(gco,''String'')),close;interfata(A,R,L,f,lista,N)');
        zfigura = uicontrol('Style','Text',...
           'Units','Normalized',...
           'Position',[0.755 0.328 0.04 0.04],...
           'BackgroundColor','w',...
           'FontSize',12,...
           'String',num2str(z));
  

     case 2 %Afisare tensiune si curent pe rezistenta
      
         subplot('position',[0.5 0.715 0.4 0.20]);
         plot(t,vr,'g');
         grid on;
         title('Tensiune pe R');
         xlabel('timp [s]');
         ylabel('Amplitudine [ V ]');
         
        
         subplot('position',[0.5 0.4 0.4 0.20]);
         plot(t,ir,'y');
         grid on;
         title('Curentul pe R');
         xlabel('timp [s]');
         ylabel('Amplitudine [ A ]');
if((faza~=0))        
subplot('position',[0.5 0.085 0.4 0.20]);
yyaxis left 
plot(t,vr,'g');
title('Defazaj');
ylabel('Tensiune');
yyaxis right
plot(t,ir,'y');
ylabel('Curent');
legend('V','A');
else 
    disp('Faza este zero');
    msgbox('Faza este zero','Warning');
end


    case 3 %Afisare tensiune si curent pe bobina
        subplot('position',[0.5 0.715 0.4 0.20]);
         plot(t,vl,'black');
         grid on;
         title('Tensiune pe L');
         xlabel('timp [s]');
         ylabel('Amplitudine [ V ]');
         
         subplot('position',[0.5 0.4 0.4 0.20]);
         plot(t,il,'c');
         grid on;
         title('Curentul pe L');
         xlabel('timp [s]');
         ylabel('Amplitudine [ A ]');
if((faza~=0))    
subplot('position',[0.5 0.085 0.4 0.20]);
yyaxis left 
plot(t,vl,'black');
title('Defazaj');
ylabel('Tensiune');
yyaxis right
plot(t,il,'c');
ylabel('Curent');
legend('V','A');
else 
    disp('Faza este zero');
    msgbox('Faza este zero','Warning');
end

case 4 % Diagrama putere [W]
          
      subplot('position',[0.5 0.715 0.4 0.20]);
        plot(t,p,'r');
        grid on;
        title('Putere disipata pe R');
        xlabel('timp [s]');
        ylabel('Putere [W]'); 
        
        subplot('position',[0.5 0.4 0.4 0.20]);
        plot(t,WmL,'r');
        grid on;
        title('Energia magnetica stocata de L ');
        xlabel('timp [s]');
        ylabel('Energie [J]');  
        
end


